replace_sensor:
  description: Replaces an external sensor
  # target:
  #   entity:
  #     domain: plant
  fields:
    meter_entity:
      name: Meter entity
      description: The meter entity to replace the sensor for
      example: plant.my_plant_current_temperature
      required: true
      selector:
        entity:
          domain: sensor
          integration: plant

    new_sensor:
      name: Sensor entity
      description: Entity id of the new sensor. Leave blank to remove sensor.
      example: sensor.new_temperature_outdoor
      required: false
      selector:
        entity:
          domain: sensor

update_plants:
  description: Force recalculation of watering frequency for all or specific plants.
  fields:
    entity_id:
      name: Entity
      description: Name of the plant entities to update.
      required: false
      selector:
        entity:
          domain: plant
          multiple: true

watered:
  description: Mark the plant as watered. This updates the last watered timestamp.
  fields:
    entity_id:
      name: Entity
      description: The plant entity to mark as watered
      required: true
      selector:
        entity:
          domain: plant

snooze:
  description: Snooze the watering notification for 1 hour.
  fields:
    entity_id:
      name: Entity
      description: The plant entity to snooze
      required: true
      selector:
        entity:
          domain: plant

skip_watering:
  description: Indicate that the plant does not need watering right now. This will delay the next watering time.
  fields:
    entity_id:
      name: Entity
      description: The plant entity
      required: true
      selector:
        entity:
          domain: plant

remove_plant:
  description: Completely remove a plant and all its associated data from Home Assistant.
  fields:
    entity_id:
      name: Entity
      description: The plant entity to remove
      required: true
      selector:
        entity:
          domain: plant
