replace_sensor:
  description: Replaces an external sensor
  # target:
  #   entity:
  #     domain: plant
  fields:
    meter_entity:
      name: Meter entity
      description: The meter entity to replace the sensor for
      example: plant.my_plant_current_temperature
      required: true
      selector:
        entity:
          domain: sensor
          integration: plant

    new_sensor:
      name: Sensor entity
      description: Entity id of the new sensor. Leave blank to remove sensor.
      example: sensor.new_temperature_outdoor
      required: false
      selector:
        entity:
          domain: sensor

update_plants:
  description: Force recalculation of watering frequency for all or specific plants.
  fields:
    entity_id:
      name: Entity
      description: Name of the plant entities to update.
      required: false
      selector:
        entity:
          domain: plant
          multiple: true
